# Generated by Django 6.0 on 2025-12-21 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='diary',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='장소명'),
        ),
        migrations.AddField(
            model_name='diary',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6, verbose_name='인증 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='만료 시간')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 완료')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '이메일 인증 토큰',
                'verbose_name_plural': '이메일 인증 토큰들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6, verbose_name='인증 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='만료 시간')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '비밀번호 재설정 토큰',
                'verbose_name_plural': '비밀번호 재설정 토큰들',
                'ordering': ['-created_at'],
            },
        ),
    ]
