# Generated by Django 6.0 on 2025-12-21 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_add_push_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['user', '-created_at'], name='diary_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['user', 'emotion'], name='diary_user_emotion_idx'),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['created_at'], name='diary_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['user', 'location_name'], name='diary_user_location_idx'),
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['user', 'is_active'], name='push_user_active_idx'),
        ),
    ]
