# Generated by Django 6.0 on 2025-12-21 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_add_database_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='태그명')),
                ('color', models.CharField(default='#6366F1', help_text='HEX 색상 코드 (예: #6366F1)', max_length=7, verbose_name='태그 색상')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_tags', to='diary.diary')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_tags', to='diary.tag')),
            ],
            options={
                'verbose_name': '일기 태그',
                'verbose_name_plural': '일기 태그들',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', '라이트 모드'), ('dark', '다크 모드'), ('system', '시스템 설정')], default='system', max_length=10, verbose_name='테마')),
                ('language', models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語')], default='ko', max_length=5, verbose_name='언어')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='푸시 알림 허용')),
                ('daily_reminder_enabled', models.BooleanField(default=False, verbose_name='일기 작성 알림')),
                ('daily_reminder_time', models.TimeField(blank=True, help_text='매일 이 시간에 일기 작성 알림을 보냅니다', null=True, verbose_name='일기 알림 시간')),
                ('auto_emotion_analysis', models.BooleanField(default=True, help_text='일기 저장 시 자동으로 감정 분석', verbose_name='자동 감정 분석')),
                ('show_location', models.BooleanField(default=True, verbose_name='위치 정보 표시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 설정',
                'verbose_name_plural': '사용자 설정들',
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='tag_user_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='diarytag',
            unique_together={('diary', 'tag')},
        ),
    ]
