# Generated by Django 6.0 on 2025-12-21 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_tag_diarytag_userpreference_tag_tag_user_name_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('system', '시스템 템플릿'), ('user', '사용자 템플릿')], default='user', max_length=10, verbose_name='템플릿 유형')),
                ('category', models.CharField(choices=[('daily', '일상'), ('gratitude', '감사'), ('goal', '목표'), ('reflection', '회고'), ('emotion', '감정'), ('travel', '여행'), ('exercise', '운동'), ('custom', '커스텀')], default='daily', max_length=20, verbose_name='카테고리')),
                ('name', models.CharField(max_length=50, verbose_name='템플릿 이름')),
                ('emoji', models.CharField(default='📝', max_length=10, verbose_name='아이콘')),
                ('description', models.CharField(max_length=200, verbose_name='설명')),
                ('content', models.TextField(verbose_name='템플릿 내용')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='사용 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='시스템 템플릿은 user=null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_templates', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '일기 템플릿',
                'verbose_name_plural': '일기 템플릿들',
                'ordering': ['-use_count', 'name'],
            },
        ),
    ]
