"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables first
load_dotenv()

# =============================================================================
# Sentry 모니터링 설정 (에러 추적)
# https://sentry.io 에서 프로젝트 생성 후 DSN 발급
# =============================================================================
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

SENTRY_DSN = os.environ.get('SENTRY_DSN', '')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style="url",
                middleware_spans=True,
            ),
            LoggingIntegration(
                level=None,  # Capture all logs
                event_level="ERROR",  # Send ERROR+ as events
            ),
        ],
        # 환경 구분
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'development'),
        
        # 성능 모니터링 (샘플링 비율)
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        
        # 프로파일링 (성능 병목 분석)
        profiles_sample_rate=float(os.environ.get('SENTRY_PROFILES_SAMPLE_RATE', '0.1')),
        
        # PII(개인정보) 전송 여부 - False로 유지 권장
        send_default_pii=False,
        
        # 릴리즈 버전 (Git 커밋 해시로 자동 설정 가능)
        release=os.environ.get('SENTRY_RELEASE', 'ai-emotion-diary@1.0.0'),
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-!6195=+z#=!sdqa5=9ec$hab=$tj0g69y0mba+j#c9vl51hqjw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# 허용 호스트 (프로덕션에서는 환경 변수로 설정)
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_yasg',  # Swagger/OpenAPI 문서
    # Local apps
    'diary',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# OpenAI API Key
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# 일기 내용 암호화 키 (32바이트 Base64 인코딩)
# 프로덕션에서는 반드시 환경 변수로 설정할 것!
# 생성 방법: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
DIARY_ENCRYPTION_KEY = os.environ.get('DIARY_ENCRYPTION_KEY', '')

# =============================================================================
# 이메일 설정 (비밀번호 재설정용)
# =============================================================================
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 
    'django.core.mail.backends.console.EmailBackend'  # 개발: 콘솔 출력
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@emotionaldiary.com')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'diary': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
    },
}

# Django REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',  # 파일 업로드 지원
        'rest_framework.parsers.FormParser',
    ],
    # 페이지네이션 설정
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # 커스텀 예외 핸들러
    'EXCEPTION_HANDLER': 'config.exception_handler.custom_exception_handler',
    
    # ==========================================================================
    # Rate Limiting (속도 제한) 설정
    # 브루트포스 공격, DDoS, API 남용 방지
    # ==========================================================================
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # 기본 제한 (모든 엔드포인트에 적용)
        'anon': '100/hour',           # 비로그인 사용자: 시간당 100회
        'user': '1000/hour',          # 로그인 사용자: 시간당 1000회
        
        # 민감한 엔드포인트별 제한 (커스텀 Throttle 클래스에서 사용)
        'login': '5/min',             # 로그인: 분당 5회 (브루트포스 방지)
        'register': '5/hour',         # 회원가입: 시간당 5회 (스팸 계정 방지)
        'password_reset': '3/hour',   # 비밀번호 재설정: 시간당 3회 (이메일 폭탄 방지)
        'email_resend': '3/10min',    # 이메일 재전송: 10분당 3회
        'ai_image': '20/day',         # AI 이미지 생성: 일당 20회 (비용 관리)
        'transcription': '30/hour',   # 음성 인식: 시간당 30회 (비용 관리)
        
        # DDoS 기본 방어
        'burst': '10/second',         # 버스트 제한: 초당 10회
        'sustained': '10000/day',     # 지속적 사용: 일당 10000회
    },
}

# Simple JWT 설정
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS 설정 (Cross-Origin Resource Sharing)
# 프론트엔드에서 백엔드 API 호출을 허용하기 위한 설정

# 개발 환경에서는 모든 도메인 허용 (배포 시 False로 변경)
CORS_ALLOW_ALL_ORIGINS = DEBUG

# 배포 환경에서 허용할 도메인 목록
CORS_ALLOWED_ORIGINS = [
    # 로컬 개발 환경
    "http://localhost:3000",      # React 웹 개발 서버
    "http://127.0.0.1:3000",
    "http://localhost:8000",      # Django 개발 서버
    "http://127.0.0.1:8000",
    "http://localhost:19006",     # Expo 웹 개발 서버
    "http://127.0.0.1:19006",
    # 모바일 앱 (Expo)
    "exp://localhost:8081",
    # TODO: 배포 환경 도메인 추가
    # "https://your-production-domain.com",
]

# 허용할 HTTP 메서드
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# 허용할 HTTP 헤더
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# 자격 증명(쿠키, Authorization 헤더 등) 허용
CORS_ALLOW_CREDENTIALS = True

# Preflight 요청 캐시 시간 (초)
CORS_PREFLIGHT_MAX_AGE = 86400  # 24시간